name: Linters

on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/linters.yml'
      - '!.github/CONTRIBUTING.md'
  pull_request:
    # We want all branches so we configure types to be the GH default again
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/linters.yml'
      - '!.github/CONTRIBUTING.md'

env:
  YARN_ENABLE_GLOBAL_CACHE: false

jobs:
  lint_js:
    name: Lint JavaScript/TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run:
          echo "dir=$(corepack yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        # List all projects that use a custom ESLint config:
        run:
          corepack yarn workspaces focus @uppy/angular @uppy-example/angular
          @uppy-example/react-native-expo @uppy/react-native @uppy-dev/build
      - name: Run linter
        run: corepack yarn run lint
      - name: Run Prettier
        run: corepack yarn run format:check-diff

  lint_md:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run:
          echo "dir=$(corepack yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: corepack yarn workspaces focus @uppy-dev/build
      - name: Run linter
        run: corepack yarn run lint:markdown

  lint_docs:
    name: Lint Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Uppy.io sources
        uses: actions/checkout@v4
        with:
          repository: transloadit/uppy.io
      - run: rm -rf docs # the other PR has not landed
      - name: Checkout docs
        uses: actions/checkout@v4
        with:
          path: uppy
      - run: mv uppy /tmp/uppy && ln -s /tmp/uppy/docs docs
      - name: Install dependencies
        run: corepack yarn --immutable
      - name: Lint files
        run: corepack yarn lint
      - name: Test build website
        run: corepack yarn build
